name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get GitHub OIDC token
        id: idtoken
        uses: actions/github-script@v6
        with:
          script: |
            return await getIDToken();  # Use getIDToken() directly
          result-encoding: string

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "/"         # Adjust if needed
          api_location: ""          # Optional
          output_location: ""       # Optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
