name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # Required for OIDC
      contents: read       # Required to access repo content

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get GitHub OIDC token
        id: idtoken
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const token = await core.getIDToken();
            return token;
          result-encoding: string

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "/"         # Adjust if your app is in a subfolder
          api_location: ""          # Leave blank if not using an API
          output_location: ""       # Adjust if you build to a dist or build folder
          github_id_token: ${{ steps.idtoken.outputs.result }}
