name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:  # This enables checks for PRs (like Dependabot PRs)

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "/"          # Adjust if your app is in a subfolder
          api_location: ""           # Optional
          output_location: ""        # Optional
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          skip_deploy_on_missing_secrets: true
