name: Secret Presence Check

on:
  push:
    branches:
      - main

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret exists
        run: |
          if [ -z "$AZURE_STATIC_WEB_APPS_API_TOKEN" ]; then
            echo "Secret is NOT set or not accessible!"
            exit 1
          else
            echo "Secret is accessible."
          fi
